name: bench-daachorse

on:
  workflow_dispatch:
  push:
    branches:
      - bench-daachorse

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: modify name of crate including our proposal methods
        run: |
          cd rust/daachorse_new_constr
          sed -e 's/name = "daachorse"/name = "daachorse_new_constr"/' -i Cargo.toml

      - name: run benchmark
        run: |
          cd rust
          chmod +x *.sh
          make

      - name: push benchmark results
        uses: EndBug/add-and-commit@v9
        with:
          add: 'rust/mdtb.md'
