name: bench-crawdad

on:
  workflow_dispatch:
  push:
    branches:
      - bench-crawdad

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: modify name of crate including our proposal methods
        run: |
          cd rust/crawdad_new_constr
          git apply ../crawdad.patch
          
      - name: download datasets
        env: 
          JAWIKI: https://dumps.wikimedia.org/jawiki/latest/jawiki-latest-all-titles-in-ns0.gz 
          ZHWIKI: https://dumps.wikimedia.org/zhwiki/latest/zhwiki-latest-all-titles-in-ns0.gz
          KOWIKI: https://dumps.wikimedia.org/kowiki/latest/kowiki-latest-all-titles-in-ns0.gz
        run: |
          cd data
          for url in $JAWIKI $ZHWIKI $KOWIKI; do
            wget -q $url
            gzip -d $(basename $url)
            realpath --relative-to ../rust $(basename ${url%.gz}) >> dataset_list.txt
          done

      - name: run benchmark
        run: |
          cd rust
          chmod +x *.sh
          make

      - name: push benchmark results
        uses: EndBug/add-and-commit@v9
        with:
          add: 'rust/mdtb.md'
